PREFIX dcat: <http://www.w3.org/ns/dcat#>

select  ?uri ?url where {
	{ graph ?g {
		?uri a dcat:Distribution ;
       dcat:downloadUrl ?url .
	}
	} union {
		?uri a dcat:Distribution ;
      dcat:downloadUrl ?url .
	}
}

